/*
Deployment script for ParkingSpace_TEST

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ParkingSpace_TEST"
:setvar DefaultFilePrefix "ParkingSpace_TEST"
:setvar DefaultDataPath "D:\MSSQL\Data\MSSQL15.PLAYGROUND\MSSQL\DATA\"
:setvar DefaultLogPath "D:\MSSQL\Data\MSSQL15.PLAYGROUND\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Parking_Group]...';


GO
CREATE TABLE [dbo].[Parking_Group] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (200) NOT NULL,
    CONSTRAINT [PK_Parking_Group_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Parking_Place]...';


GO
CREATE TABLE [dbo].[Parking_Place] (
    [Id]      INT            IDENTITY (1, 1) NOT NULL,
    [GroupId] INT            NOT NULL,
    [Number]  NVARCHAR (100) NOT NULL,
    [Comment] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Parking_Place_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Parking_Group_Id_Parking_Place_GroupId]...';


GO
ALTER TABLE [dbo].[Parking_Place] WITH NOCHECK
    ADD CONSTRAINT [FK_Parking_Group_Id_Parking_Place_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Parking_Group] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Parking_Place] WITH CHECK CHECK CONSTRAINT [FK_Parking_Group_Id_Parking_Place_GroupId];


GO
PRINT N'Update complete.';


GO
