/*
Deployment script for ParkingSpace_TEST

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ParkingSpace_TEST"
:setvar DefaultFilePrefix "ParkingSpace_TEST"
:setvar DefaultDataPath "D:\MSSQL\Data\MSSQL15.PLAYGROUND\MSSQL\DATA\"
:setvar DefaultLogPath "D:\MSSQL\Data\MSSQL15.PLAYGROUND\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating Table [dbo].[User]...';


GO
CREATE TABLE [dbo].[User] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Firstname]   NVARCHAR (100) NOT NULL,
    [Lastname]    NVARCHAR (100) NULL,
    [Email]       NVARCHAR (200) NOT NULL,
    [IsEnabled]   BIT            NOT NULL,
    [DateCreated] DATETIME       NOT NULL,
    CONSTRAINT [PK_User_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[User].[IX_User_Email_Unique]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_User_Email_Unique]
    ON [dbo].[User]([Email] ASC);


GO
PRINT N'Creating Default Constraint [dbo].[DF_User_IsEnabled_True]...';


GO
ALTER TABLE [dbo].[User]
    ADD CONSTRAINT [DF_User_IsEnabled_True] DEFAULT (1) FOR [IsEnabled];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Posting_DateCreated_UtcDate]...';


GO
ALTER TABLE [dbo].[User]
    ADD CONSTRAINT [DF_Posting_DateCreated_UtcDate] DEFAULT (GETUTCDATE()) FOR [DateCreated];


GO
PRINT N'Update complete.';


GO
